#! /bin/bash

if [ -z "$1" ]
	then
		python namsel.py preprocess ./data
	else
		python namsel.py preprocess --threshold=$1 ./data
fi
python namsel.py recognize-volume --format text --page_type pecha --line_break_method line_cluster ./data/out
mv ocr_output.txt ./data
rm -R ./data/out