#! /bin/bash -x

if [ $# -eq 2 ]
then
	if [[ $1 =~ ^-?[0-9]+$ ]]
	then
		python namsel.py preprocess --threshold=$1 ./data
	elif [[ $2 =~ ^-?[0-9]+$ ]]
	then
		python namsel.py preprocess --threshold=$2 ./data
	else
		python namsel.py preprocess ./data
	fi
elif [[ $1 =~ ^-?[0-9]+$ ]]
then
	python namsel.py preprocess --threshold=$1 ./data
else
	python namsel.py preprocess ./data
fi
python namsel.py recognize-volume --format text --page_type pecha --line_break_method line_cluster ./data/out
if [ -f ./ocr_output.txt ]
then
	mv ocr_output.txt ./data
fi
if [ -d ./data/out ]
then
	rm -R ./data/out
fi