#! /bin/bash -x

if [ -d ./data/out ]
then
	dir="./data/out"
else
	dir="./data"
fi
python namsel.py recognize-volume --format text --page_type book --line_break_method line_cut --clear_hr True $dir
if [ -f ./ocr_output.txt ]
then
	mv ocr_output.txt ./data
fi
if [ -d ./data/out ]
then
	rm -R ./data/out
fi