#! /bin/bash -x

if [ $1 == "preprocess" ]
then
	dir="./data"
elif [ -d ./data/out ]
then
	dir="./data/out"
else
	dir="./data"
fi
python namsel.py $* $dir
if [ $1 != "preprocess" ] && [ -f ./ocr_output.txt ]
then
	mv ocr_output.txt ./data
fi