#! /bin/bash -x

if [ $# -eq 2 ]
then
	if [[ $1 =~ ^-?[0-9]+$ ]] && [ $2 == "l2" ]
	then
		python namsel.py preprocess --threshold=$1 --layout double ./data
	elif [ $1 == "l2" ] && [[ $2 =~ ^-?[0-9]+$ ]]
	then
		python namsel.py preprocess --threshold=$2 --layout double ./data
	elif [ $1 == "l2" ] && [ $2 == "l2" ]
	then
		python namsel.py preprocess --layout double ./data
	elif [[ $1 =~ ^-?[0-9]+$ ]] && [[ $2 =~ ^-?[0-9]+$ ]]
	then
		python namsel.py preprocess --threshold=$1 ./data
	elif [ $1 == "l2" ]
	then
		python namsel.py preprocess --layout double ./data
	elif [[ $1 =~ ^-?[0-9]+$ ]]
	then
		python namsel.py preprocess --threshold=$1 ./data
	elif [ $2 == "l2" ]
	then
		python namsel.py preprocess --layout double ./data
	elif [[ $2 =~ ^-?[0-9]+$ ]]
	then
		python namsel.py preprocess --threshold=$2 ./data
	else
		python namsel.py preprocess ./data
	fi
elif [ $1 == "l2" ]
then
	python namsel.py preprocess --layout double ./data
elif [[ $1 =~ ^-?[0-9]+$ ]]
then
	python namsel.py preprocess --threshold=$1 ./data
else
	python namsel.py preprocess ./data
fi